// Fetch all outloading freights
export const OUTLOADING_FREIGHTS_REQUEST = 'OUTLOADING_FREIGHTS_REQUEST';
export const OUTLOADING_FREIGHTS_RECEIVE = 'OUTLOADING_FREIGHTS_RECEIVE';
export const OUTLOADING_FREIGHTS_FAIL = 'OUTLOADING_FREIGHTS_FAIL';

// Fetch all delivered freights
export const DELIVERED_FREIGHTS_REQUEST = 'DELIVERED_FREIGHTS_REQUEST';
export const DELIVERED_FREIGHTS_RECEIVE = 'DELIVERED_FREIGHTS_RECEIVE';
export const DELIVERED_FREIGHTS_FAIL = 'DELIVERED_FREIGHTS_FAIL';

// fetch single freight
export const SINGLE_FREIGHT_REQUEST = 'SINGLE_FREIGHT_REQUEST';
export const SINGLE_FREIGHT_RECEIVE = 'SINGLE_FREIGHT_RECEIVE';
export const SINGLE_FREIGHT_FAIL = 'SINGLE_FREIGHT_FAIL';

// scanned for outloading
export const SCANNED_FREIGHT_REQUEST = 'SCANNED_FREIGHT_REQUEST';
export const SCANNED_OUTLOADING_RECEIVE = 'SCANNED_OUTLOADING_RECEIVE';
export const SCANNED_OUTLOADING_FAIL = 'SCANNED_OUTLOADING_FAIL';
export const SCANNED_FREIGHT_NUMBER = 'SCANNED_FREIGHT_NUMBER';

// scanned for delivery
export const SCANNED_DELIVERY_RECEIVE = 'SCANNED_DELIVERY_RECEIVE';
export const SCANNED_DELIVERY_FAIL = 'SCANNED_DELIVERY_FAIL';

// Auth
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_USER_RECEIVE = 'AUTHENTICATION_USER_REVECIVE';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';

// Register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_USER_CREATED = 'REGISTER_USER_CREATED';
export const REGISTER_USER_EXISTS = 'REGISTER_USER_EXISTS';
export const REGISTER_NO_MESSAGE = 'REGISTER_NO_MESSAGE';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// Employee All freights
export const USER_OUTLOADING_FREIGHTS_REQUEST = 'USER_OUTLOADING_FREIGHTS_REQUEST';
export const USER_OUTLOADING_FREIGHTS_RECEIVE = 'USER_OUTLOADING_FREIGHTS_RECEIVE';
export const USER_OUTLOADING_FREIGHTS_FAIL = 'USER_OUTLOADING_FREIGHTS_FAIL';
export const USER_DELIVERED_FREIGHTS_REQUEST = 'USER_DELIVERED_FREIGHTS_FAIL';
export const USER_DELIVERED_FREIGHTS_RECEIVE = 'USER_DELIVERED_FREIGHTS_RECEIVE';
export const USER_DELIVERED_FREIGHTS_FAIL = 'USER_DELIVERED_FREIGHTS_FAIL';